### ISSUE TITLE
"Hmmm... cannot reach this page" error is shown after user clicks on Allow button on OAuth Window

### ISSUE THREAD

**Issue by abhinovpankaj** [gsuitedevs/dotnet-samples#14]
Name: Unable to fetch tokens once User accept the Consent on OAuth screen. "Hmmm... cannot reach this page" error is shown.

Earlier this was working and now It has stopped working I am not sure if anything has been modified.
## Expected Behavior
User should be able to allow the app to access Sheets, and No exception should be thrown.

## Steps to Reproduce the Problem
Follow steps as per article 
https://developers.google.com/sheets/api/quickstart/dotnet

## Specifications
  - Tried on Edge and Google Chrome
  - .NET version:4.5.2
  - OS (Mac/Linux/Windows):Windows 10
  - Using Visual Studio 2015

**Comment by abhinovpankaj** [comment]
Exception Message:
Failed to launch browser with "https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&response_type=code&client_id=620656717901-k5umr1re3-----------------------*****apps.googleusercontent.com&redirect_uri=http%3A%2F%2F127.0.0.1%3A62406%2Fauthorize%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fspreadsheets.readonly" for authorization. See inner exception for details.

**Comment by abhinovpankaj** [comment]
> > See inner exception for details.
> 
> Can you please post that inner exception as well?
Inner Exception Message:
Dispatcher processing has been suspended, but messages are still being processed.

Stacktrace:

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at Microsoft.Win32.NativeMethods.ShellExecuteEx(ShellExecuteInfo info)
   at System.Diagnostics.ShellExecuteHelper.ShellExecuteFunction()
   at System.Diagnostics.ShellExecuteHelper.ShellExecuteOnSTAThread()
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Google.Apis.Auth.OAuth2.LocalServerCodeReceiver.<ReceiveCodeAsync>d__14.MoveNext()

**Comment by erickoledadevrel** [comment]
Thanks. Unfortunately that error isn't very descriptive. I don't see any record of others running into this error before either, so I'm not sure what the cause could be. Is there anything special about your environment that could be causing an issue?

**Comment by nguyenthanhliemfc** [comment]
My [sample code here](https://github.com/nguyenthanhliemfc/App1) please take a look when you have free time

**Comment by erickoledadevrel** [comment]
@nguyenthanhliemfc - The auth flow shown in these samples will only work in a desktop environment. More information about the different auth options is available here:

https://developers.google.com/api-client-library/dotnet/guide/aaa_oauth

@abhinovpankaj - Is your app also running on Xamarin?

**Comment by nguyenthanhliemfc** [comment]
Its same error when I test on UWP too!

**Comment by abhinovpankaj** [comment]
> @nguyenthanhliemfc - The auth flow shown in these samples will only work in a desktop environment. More information about the different auth options is available here:
> 
> https://developers.google.com/api-client-library/dotnet/guide/aaa_oauth
> 
> @abhinovpankaj - Is your app also running on Xamarin?

No, I am running a WPF Application.

**Comment by erickoledadevrel** [comment]
The samples in this repo will only work for console applications. For other application types, please see the auth guide I linked to above.

**Comment by abhinovpankaj** [comment]
The same method has been used as mentioned above in the oauth links..
For installed application , the sample code has used user credentials and
AunthticatebrokerAsync which is what I am using too.

Thanks
Abhinov

**Comment by nguyenthanhliemfc** [comment]
@abhinovpankaj Is it work?

**Comment by abhinovpankaj** [comment]
> @abhinovpankaj Is it work?

No it doesn't. Once I get time I will create one sample app and upload it.
For the time being you can use GoogleCredential class. For this you will have to create Service credentials and provide access to that service account on the google sheet you are connecting to.
